'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
 Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
Partial Friend NotInheritable Class MySettings
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
    
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
    
    Public Shared ReadOnly Property [Default]() As MySettings
        Get
            
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property LASTMEDIATITLE() As String
        Get
            Return CType(Me("LASTMEDIATITLE"),String)
        End Get
        Set
            Me("LASTMEDIATITLE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property LASTPLAYLIST() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("LASTPLAYLIST"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("LASTPLAYLIST") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property LASTMEDIASEEK() As Double
        Get
            Return CType(Me("LASTMEDIASEEK"),Double)
        End Get
        Set
            Me("LASTMEDIASEEK") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property LASTMEDIADURATION() As Double
        Get
            Return CType(Me("LASTMEDIADURATION"),Double)
        End Get
        Set
            Me("LASTMEDIADURATION") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property LASTMEDIAINDEX() As Integer
        Get
            Return CType(Me("LASTMEDIAINDEX"),Integer)
        End Get
        Set
            Me("LASTMEDIAINDEX") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property DEFAULTTHEME() As Integer
        Get
            Return CType(Me("DEFAULTTHEME"),Integer)
        End Get
        Set
            Me("DEFAULTTHEME") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property LIBRARIESPATH() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("LIBRARIESPATH"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("LIBRARIESPATH") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property USEANIMATIONS() As Boolean
        Get
            Return CType(Me("USEANIMATIONS"),Boolean)
        End Get
        Set
            Me("USEANIMATIONS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property FX_EQ() As Global.Un4seen.Bass.BASS_DX8_PARAMEQ
        Get
            Return CType(Me("FX_EQ"),Global.Un4seen.Bass.BASS_DX8_PARAMEQ)
        End Get
        Set
            Me("FX_EQ") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property FX_REVERB() As Global.Un4seen.Bass.BASS_DX8_REVERB
        Get
            Return CType(Me("FX_REVERB"),Global.Un4seen.Bass.BASS_DX8_REVERB)
        End Get
        Set
            Me("FX_REVERB") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property USEDISCORDRPC() As Boolean
        Get
            Return CType(Me("USEDISCORDRPC"),Boolean)
        End Get
        Set
            Me("USEDISCORDRPC") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property FX_DAMP() As Global.Un4seen.Bass.AddOn.Fx.BASS_BFX_DAMP
        Get
            Return CType(Me("FX_DAMP"),Global.Un4seen.Bass.AddOn.Fx.BASS_BFX_DAMP)
        End Get
        Set
            Me("FX_DAMP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property LASTMEDIATYPE() As Integer
        Get
            Return CType(Me("LASTMEDIATYPE"),Integer)
        End Get
        Set
            Me("LASTMEDIATYPE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property LASTMEDIAARTIST() As String
        Get
            Return CType(Me("LASTMEDIAARTIST"),String)
        End Get
        Set
            Me("LASTMEDIAARTIST") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property LASTMEDIA() As String
        Get
            Return CType(Me("LASTMEDIA"),String)
        End Get
        Set
            Me("LASTMEDIA") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property LASTMEDIAYEAR() As Integer
        Get
            Return CType(Me("LASTMEDIAYEAR"),Integer)
        End Get
        Set
            Me("LASTMEDIAYEAR") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property MUSICBRAINZNOTIFY() As Boolean
        Get
            Return CType(Me("MUSICBRAINZNOTIFY"),Boolean)
        End Get
        Set
            Me("MUSICBRAINZNOTIFY") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property LYRICSNOTIFY() As Boolean
        Get
            Return CType(Me("LYRICSNOTIFY"),Boolean)
        End Get
        Set
            Me("LYRICSNOTIFY") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property BACKGROUNDTYPE() As Integer
        Get
            Return CType(Me("BACKGROUNDTYPE"),Integer)
        End Get
        Set
            Me("BACKGROUNDTYPE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property MEDIABAR_ANIMTYPE() As Integer
        Get
            Return CType(Me("MEDIABAR_ANIMTYPE"),Integer)
        End Get
        Set
            Me("MEDIABAR_ANIMTYPE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property FAVOURITETRACKS() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("FAVOURITETRACKS"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("FAVOURITETRACKS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property HOME_SHOWVISUALISER() As Boolean
        Get
            Return CType(Me("HOME_SHOWVISUALISER"),Boolean)
        End Get
        Set
            Me("HOME_SHOWVISUALISER") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ONMEDIACHANGE_FADEAUDIO() As Boolean
        Get
            Return CType(Me("ONMEDIACHANGE_FADEAUDIO"),Boolean)
        End Get
        Set
            Me("ONMEDIACHANGE_FADEAUDIO") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property STREAMDOWNLOADERNOTIFY() As Boolean
        Get
            Return CType(Me("STREAMDOWNLOADERNOTIFY"),Boolean)
        End Get
        Set
            Me("STREAMDOWNLOADERNOTIFY") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property NOTIFICATIONTTS() As Boolean
        Get
            Return CType(Me("NOTIFICATIONTTS"),Boolean)
        End Get
        Set
            Me("NOTIFICATIONTTS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property FX_BALANCE() As Single
        Get
            Return CType(Me("FX_BALANCE"),Single)
        End Get
        Set
            Me("FX_BALANCE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property FX_SAMPLERATE() As Single
        Get
            Return CType(Me("FX_SAMPLERATE"),Single)
        End Get
        Set
            Me("FX_SAMPLERATE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property ONERRORSHOW() As Integer
        Get
            Return CType(Me("ONERRORSHOW"),Integer)
        End Get
        Set
            Me("ONERRORSHOW") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property SUPRESSERRORS() As Boolean
        Get
            Return CType(Me("SUPRESSERRORS"),Boolean)
        End Get
        Set
            Me("SUPRESSERRORS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ALLOWGLOBALHOTKEYS() As Boolean
        Get
            Return CType(Me("ALLOWGLOBALHOTKEYS"),Boolean)
        End Get
        Set
            Me("ALLOWGLOBALHOTKEYS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("179")>  _
    Public Property GLOBALHOTKEY_PLAYPAUSE() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_PLAYPAUSE"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_PLAYPAUSE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property GLOBALHOTKEY_PLAYPAUSE_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_PLAYPAUSE_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_PLAYPAUSE_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("118")>  _
    Public Property GLOBALHOTKEY_NEXT() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_NEXT"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_NEXT") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property GLOBALHOTKEY_NEXT_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_NEXT_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_NEXT_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("116")>  _
    Public Property GLOBALHOTKEY_PREVIOUS() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_PREVIOUS"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_PREVIOUS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property GLOBALHOTKEY_PREVIOUS_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_PREVIOUS_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_PREVIOUS_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("119")>  _
    Public Property GLOBALHOTKEY_SKIP10() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_SKIP10"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_SKIP10") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property GLOBALHOTKEY_SKIP10_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_SKIP10_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_SKIP10_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("117")>  _
    Public Property GLOBALHOTKEY_BACK10() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_BACK10"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_BACK10") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property GLOBALHOTKEY_BACK10_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_BACK10_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_BACK10_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("175")>  _
    Public Property GLOBALHOTKEY_VOLUMEUP() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_VOLUMEUP"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_VOLUMEUP") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property GLOBALHOTKEY_VOLUMEUP_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_VOLUMEUP_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_VOLUMEUP_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("174")>  _
    Public Property GLOBALHOTKEY_VOLUMEDOWN() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_VOLUMEDOWN"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_VOLUMEDOWN") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property GLOBALHOTKEY_VOLUMEDOWN_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_VOLUMEDOWN_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_VOLUMEDOWN_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("173")>  _
    Public Property GLOBALHOTKEY_VOLUMEMUTE() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_VOLUMEMUTE"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_VOLUMEMUTE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property GLOBALHOTKEY_VOLUMEMUTE_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_VOLUMEMUTE_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_VOLUMEMUTE_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("")>  _
    Public Property LIBRARY_PATH() As String
        Get
            Return CType(Me("LIBRARY_PATH"),String)
        End Get
        Set
            Me("LIBRARY_PATH") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property SOUNDCLOUD_NOTIFY() As Boolean
        Get
            Return CType(Me("SOUNDCLOUD_NOTIFY"),Boolean)
        End Get
        Set
            Me("SOUNDCLOUD_NOTIFY") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute()>  _
    Public Property FX_STEREOMIX() As Object
        Get
            Return CType(Me("FX_STEREOMIX"),Object)
        End Get
        Set
            Me("FX_STEREOMIX") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property MINIPLAYER_SMARTCOLORS() As Boolean
        Get
            Return CType(Me("MINIPLAYER_SMARTCOLORS"),Boolean)
        End Get
        Set
            Me("MINIPLAYER_SMARTCOLORS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property CACHELIBRARYDATA() As Boolean
        Get
            Return CType(Me("CACHELIBRARYDATA"),Boolean)
        End Get
        Set
            Me("CACHELIBRARYDATA") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property ISFIRSTSTART() As Boolean
        Get
            Return CType(Me("ISFIRSTSTART"),Boolean)
        End Get
        Set
            Me("ISFIRSTSTART") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("https://github.com/AnesHamdani08/MuPlay/blob/main/Extras/Updates%20Server/MuPlayL"& _ 
        "ocalUpdatesServer.xml")>  _
    Public Property UPDATESSERVER() As String
        Get
            Return CType(Me("UPDATESSERVER"),String)
        End Get
        Set
            Me("UPDATESSERVER") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property SKIPSILENCES() As Boolean
        Get
            Return CType(Me("SKIPSILENCES"),Boolean)
        End Get
        Set
            Me("SKIPSILENCES") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("4")>  _
    Public Property PLAYLISTDRAGDROPACTION() As Integer
        Get
            Return CType(Me("PLAYLISTDRAGDROPACTION"),Integer)
        End Get
        Set
            Me("PLAYLISTDRAGDROPACTION") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("TopDirectoryOnly")>  _
    Public Property FBD_QUICKACESS_SUBFOLDERS() As Global.System.IO.SearchOption
        Get
            Return CType(Me("FBD_QUICKACESS_SUBFOLDERS"),Global.System.IO.SearchOption)
        End Get
        Set
            Me("FBD_QUICKACESS_SUBFOLDERS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property DSP_PLUGINS() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("DSP_PLUGINS"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("DSP_PLUGINS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property PLAYER_AUTOPLAY() As Boolean
        Get
            Return CType(Me("PLAYER_AUTOPLAY"),Boolean)
        End Get
        Set
            Me("PLAYER_AUTOPLAY") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property FXEQGAINS() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("FXEQGAINS"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("FXEQGAINS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property GLOBALHOTKEY_NOWPLAYING() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_NOWPLAYING"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_NOWPLAYING") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property GLOBALHOTKEY_NOWPLAYING_MOD() As Integer
        Get
            Return CType(Me("GLOBALHOTKEY_NOWPLAYING_MOD"),Integer)
        End Get
        Set
            Me("GLOBALHOTKEY_NOWPLAYING_MOD") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property API_ALLOWGET() As Boolean
        Get
            Return CType(Me("API_ALLOWGET"),Boolean)
        End Get
        Set
            Me("API_ALLOWGET") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property API_ALLOWSET() As Boolean
        Get
            Return CType(Me("API_ALLOWSET"),Boolean)
        End Get
        Set
            Me("API_ALLOWSET") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property API_LOG() As Boolean
        Get
            Return CType(Me("API_LOG"),Boolean)
        End Get
        Set
            Me("API_LOG") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
    Public Property API_ALLOWEVENTS() As Boolean
        Get
            Return CType(Me("API_ALLOWEVENTS"),Boolean)
        End Get
        Set
            Me("API_ALLOWEVENTS") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property API() As Boolean
        Get
            Return CType(Me("API"),Boolean)
        End Get
        Set
            Me("API") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("300")>  _
    Public Property API_TIMEOUT() As Integer
        Get
            Return CType(Me("API_TIMEOUT"),Integer)
        End Get
        Set
            Me("API_TIMEOUT") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("<?xml version=""1.0"" encoding=""utf-16""?>"&Global.Microsoft.VisualBasic.ChrW(13)&Global.Microsoft.VisualBasic.ChrW(10)&"<ArrayOfString xmlns:xsi=""http://www.w3."& _ 
        "org/2001/XMLSchema-instance"" xmlns:xsd=""http://www.w3.org/2001/XMLSchema"" />")>  _
    Public Property API_Plugins() As Global.System.Collections.Specialized.StringCollection
        Get
            Return CType(Me("API_Plugins"),Global.System.Collections.Specialized.StringCollection)
        End Get
        Set
            Me("API_Plugins") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property DEFAULTRESUMEACTION() As Integer
        Get
            Return CType(Me("DEFAULTRESUMEACTION"),Integer)
        End Get
        Set
            Me("DEFAULTRESUMEACTION") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property ALLOW_MULTIPLEINSTANCES() As Boolean
        Get
            Return CType(Me("ALLOW_MULTIPLEINSTANCES"),Boolean)
        End Get
        Set
            Me("ALLOW_MULTIPLEINSTANCES") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("3")>  _
    Public Property HOMEVISUALISERTYPE() As Integer
        Get
            Return CType(Me("HOMEVISUALISERTYPE"),Integer)
        End Get
        Set
            Me("HOMEVISUALISERTYPE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("1")>  _
    Public Property TABSELECTORTYPE() As Integer
        Get
            Return CType(Me("TABSELECTORTYPE"),Integer)
        End Get
        Set
            Me("TABSELECTORTYPE") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
    Public Property USECOVERCACHING() As Boolean
        Get
            Return CType(Me("USECOVERCACHING"),Boolean)
        End Get
        Set
            Me("USECOVERCACHING") = value
        End Set
    End Property
    
    <Global.System.Configuration.UserScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
    Public Property DUMMY() As Integer
        Get
            Return CType(Me("DUMMY"),Integer)
        End Get
        Set
            Me("DUMMY") = value
        End Set
    End Property
End Class

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.WpfPlayer.MySettings
            Get
                Return Global.WpfPlayer.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
